### PR TITLE
Add custom validator function

### PR DESCRIPTION
**Pull request by recanman**

### CODE REVIEW

**Comment by noahwillcrow** [comment]
Can you share an example of when and why?

**Comment by recanman** [comment]
An example:
I am using EnumList along with Knit, and I need to have a validator that checks if it is in the Enum through `self:BelongsTo(name)`. Since it’s using a custom function, and which I could check the table directly, I would rather use the function provided to me for better code readability.

Other examples can be found on the express-validator page that I linked that can be applied to roblox, for example checking it a value already exists in a data store.

**Comment by noahwillcrow** [comment]
> for better code readability

How is it more readable to wrap your custom function in something that just calls your callback? You still write your custom function. `t.custom(isMyType)`, but it's just... weird to me to do that. It's not super readable like `t.numberPositive` is.

**Comment by recanman** [comment]
Regardless, there would be some instances where I would need a custom validator, as the current ones would not suit me in every single situation. Other runtime validation libraries have this already.

**Comment by noahwillcrow** [comment]
> Other runtime validation libraries have this already.

"would you jump off a bridge just because ..."

It still feels like just using `isMyType` is way better than `t.custom(isMyType)`. It ultimately doesn't offer anything but calling your callback.

**Comment by recanman** [comment]
That is true, but I wouldn't want to create my own function to integrate it with t. Being able to wrap it gives me more consistent syntax instead of having to write:

```lua
function isInDatastore()
    return function(value)
        -- get datastore, then get data, then return true if it exists
    end
end
```

I would have to write this for every single time I want to make something similar, or make a simple class that does it for me. Why not add it into t?

With t:

```lua
local isInDatastore = t.custom(function(val)
     -- get datastore, then get data, then return true if it exists
end)
```

I immediately see from the code that I'm defining isInDatastore to a custom validator that executes some logic, rather than seeing a function that returns a function.

**Comment by noahwillcrow** [comment]
That's literally the same thing as this:

```lua
local isInDataStore = function(val)
    -- get datastore, then get data, then return true if it exists
end
```

And `t` is not meant to do validation like `isInDataStore`. `t` is a _type checking_ library. Not a wholesale validation library.

**Pull request closed without merging**
